### ISSUE TITLE
For Unreal

### ISSUE THREAD

**Issue by kohjkim** [Vital-Volkov/Stereoscopic-3D-system-for-Unity-2019-#6]
What are the ways to support the development some cost?

**Comment by kohjkim** [comment]
> 개발 비용을 지원하는 방법은 무엇입니까?

**Comment by Vital-Volkov** [comment]
I think to add donate possibility here but now you can try donate to my VISA USD card 4482130137250449

**Comment by kohjkim** [comment]
This is South Korea.
The method of overseas remittance is tricky in Korea.

1. When transferring Visa card

Only 14 countries. (Singapore, Vietnam, Philippines, Thailand, Indonesia, Malaysia, Cambodia, Germany, Russia, Spain, China, Greece, Arab Emirates, Kazakhstan)
I use the BC card.

2. When transferring  to a bank account

Each country has its own needs.
What country are you from?

3. the easiest way

If you upload  a paid product somewhere, I will buy it.
Is it possible?





-----Original Message-----

**Comment by Vital-Volkov** [comment]
Can you send to https://qiwi.com/ ? Number +79243259779

3. may be in future

**Comment by kohjkim** [comment]
If you have a bitcoin deposit address, please send  me.

**Comment by Vital-Volkov** [comment]
Binance BEP20 is OK? 
0xf33aefe4bd07feba1bd858aa4fabb608a88923a1

**Comment by kohjkim** [comment]
https://upbit.com/

Upbit(Cryptocurrency exchange)  does not support the Binance smart chain(BEP20).

I bought the XRP(Ripple, 500$) because fast(minute) in transmission. (not bitcoin)

(Caution) Do not send it over the BSC(bep20), BNB(bep2),ETH(erc20) network.

Only XRP (address and memo) netwok.

-----Original Message-----

**Comment by Vital-Volkov** [comment]
OK no problem Binance have XRP
[image: Desktop Screenshot 2023.01.19 - 22.45.56.16.png]

Address
rEb8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh

MEMO
484930939

**Comment by kohjkim** [comment]
now. 2023.01.19 20:55

I sent a part of the ripple, so please check it.
 check it out. I'll send the rest if it's okay.



-----Original Message-----

**Comment by Vital-Volkov** [comment]
OK I received 300
Thank you!

**Comment by kohjkim** [comment]
I sent the rest.

I will send it to you again if I have a chance later.

Work hard on the development.

bye.


-----Original Message-----

**Comment by Vital-Volkov** [comment]
Received 999
Thank you very much!
I`ll start working on unreal engine as soon as possible. What the project
are you working on now?

**Comment by kohjkim** [comment]
I'm working in a different field(not game).
I'm studying for Unreal Engine, a beginner.
I'm interested in anaglyph .
planning to create educational content(realistic + toon) next year.
I'll consult with you when I get a detailed plan.


-----Original Message-----

**Comment by Vital-Volkov** [comment]
Programmer?
Anaglyph is low quality. I using passive S3D monitor LG d2342p + very comfortable glassess Zalman ZM-SG100G for years + now Meta Quest 2 + Bobo VR pro head mounting and recommend it. I'll develop for VR also.

**Comment by kohjkim** [comment]
I'm not a programmer, a planner(a different industry)
It's a concept that uses red-blue glasses that don't use the machines you mentioned.
I used the unity3d(until 2022.1.0f1, hdrp) that you made, it was very easy and free to use.(only Stereo3D.cs, anaglyph color,user IPD, virtual IPD)
So, I hope to use it easily in Unreal.

(ps)
1.  I have purchased hundreds of unity3d asset, so I will send you a list if you need them.(send me a email address)
2.  Currently, s3d(unity3d) works only by pressing the play button.
    Please make it possible even when the play button is not working.

-----Original Message-----

**Comment by Vital-Volkov** [comment]
Yes, Anaglyph is the easiest method for any screen and multiple users. Sad
that 3D monitors and TV's manufacturing stopped. LG 3D was the best and I
don't know a replacement for my old D2342P monitor. I also wanted to buy an
OLED LG 3D TV but they are gone and VR is coming. I think the best solution
is a 3D projector with a silver screen and passive glasses.
First versions of my S3D system were overloaded with settings but later I
decided to make it as simple as possible for users while keeping the main
idea of scientific precision and I'll try to make the same for Unreal.

1. Impressive, interesting to see the list ***@***.***
2. OK I understand, I'll try to make S3D work in Editor mode also.

**Comment by kohjkim** [comment]
Maybe the email is private.
Your email looks like this. (***@***.***)  

Attach the Asset as a photo (Total 700, deprecated 100)
If you need anything, I will download it and send it to you.

-----Original Message-----

**Comment by kohjkim** [comment]
![1](https://user-images.githubusercontent.com/122623649/213844252-d0cb61c6-8581-4030-88d6-c08da32f2416.png)
![2](https://user-images.githubusercontent.com/122623649/213844257-b68a0cab-054d-40eb-9cb0-85009614304b.png)
![3](https://user-images.githubusercontent.com/122623649/213844259-20005f5f-e1ce-4d21-a56e-93a8070e7186.png)
![4](https://user-images.githubusercontent.com/122623649/213844261-e9731af6-b90d-4329-ac24-31f665f891ac.png)
![5](https://user-images.githubusercontent.com/122623649/213844264-ff43e2e7-6293-4258-ac36-7fcea992f6ac.png)
![6](https://user-images.githubusercontent.com/122623649/213844267-92dd3361-27a4-4b4f-b4cc-6cc63dd15b6f.png)
![7](https://user-images.githubusercontent.com/122623649/213844269-49b0d449-ec0f-447e-9ad2-20fd5b4f5eb8.png)
![8](https://user-images.githubusercontent.com/122623649/213844273-7ca2dfb9-0767-43a1-b452-cf5c0367d90c.png)
![9](https://user-images.githubusercontent.com/122623649/213844276-6f919652-78bd-41ad-bb04-f347a48b4bb6.png)
![10](https://user-images.githubusercontent.com/122623649/213844278-13fa5202-01ad-4dbd-bd26-9d27f1466782.png)
![deprecated-115](https://user-images.githubusercontent.com/122623649/213844279-6c6a5aaa-9b9b-4909-9e45-491c13d0cfc0.png)

**Comment by Vital-Volkov** [comment]
Yes I saw that email replaced in a message on github and edited it like
this - " vital.volkov gmail.com (replace space with @)" but message not
updated in email.
I also added email as a website to my profile info on github.
Ok I saved screenshots, thank you!

**Comment by kohjkim** [comment]
I sent it to your email address.
The title is (from korea / unity3d screenshot)

-----Original Message-----
